### ISSUE TITLE
Data and label correspondence issues

### ISSUE THREAD

**Issue by evinnliu** [miquelmarti/Okutama-Action#10]
Does anybody use this datesets? I am confused about the relationship between videos and labels. If i wanna use pictures to train my models, how to use the labels. Or someone have already used VATIC, but i was stucked in installing VATIC. Any advice would be greatly appreciated!

**Comment by miquelmarti** [comment]
Hi, labels are for each frame, so every image in the video. You can download the data in video format, or the corresponding frames already extracted from the video. To extract the frames of the video yourself you can use a tool like ffmpeg. Hope this helps.

**Comment by hmbb123** [comment]
If I just want to use this dataset for training person target detection model, can you provide the annotation file in coco or yolo format, or provide the conversion code?
