### ISSUE TITLE
Any concrete implementation ?

### ISSUE THREAD

**Issue by mmilunovic** [miquelmarti/Okutama-Action#4]
Hi, can you please provide some detailed implementation.

**Comment by miquelmarti** [comment]
Models are available here https://drive.google.com/drive/folders/0BydaU2Imk1zjSUpCdFpmbmtEeHc

**Comment by mmilunovic** [comment]
Hi, yeah, I found caffe models and data on google drive, but if I want to
run this I need to put it all together, that's what I was asking for.

*Miloš Milunović*
email : milunovicmilos@gmail.com
phone : +381 (0) 64 1076650

Linkedin <https://www.linkedin.com/in/milosmilunovic/> | Github
<https://github.com/mmilunovic> | Facebook
<https://www.facebook.com/milos.milunovic7> | Twitter
<https://twitter.com/FuckinLannister>
