### ISSUE TITLE
Recommended way of bulk download

### ISSUE THREAD

**Issue by fzqneo** [miquelmarti/Okutama-Action#7]
First, thank you the authors for curating the data set.

The data is currently on Google Drive under different folders. What is the recommended way to do a bulk download of the whole data set, without manually downloading each individual file? Google's zipping on-demand seems to take forever.

**Comment by miquelmarti** [comment]
The zipping can take long but it has worked in the past. Otherwise depending on your OS there should be tools to sync folders from Google Drive such as https://www.google.com/intl/en_ca/drive/download/
